/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Process.customers;
import Process.user;
import Validate.UserDTO;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import java.sql.SQLException;
import java.util.Set;
import javax.swing.JOptionPane;
import utils.PasswordUtils;

/**
 *
 * @author Nguyen Gia Huy
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null); // Hiển thị giữa màn hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jP1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jbtnRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxtFullName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jP2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jtxtAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtPhone = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLReturn = new javax.swing.JLabel();
        jCbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register2.jpg"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Đăng ký");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jtxtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 270, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mật khẩu");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 270, -1));

        jP1.setBorder(null);
        bg.add(jP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 270, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_icon2.png"))); // NOI18N
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jbtnRegister.setBackground(new java.awt.Color(0, 0, 0));
        jbtnRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegister.setText("Đăng ký");
        jbtnRegister.setToolTipText("");
        jbtnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegisterActionPerformed(evt);
            }
        });
        bg.add(jbtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Họ và tên");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jtxtFullName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jtxtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 270, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 270, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 270, -1));

        jP2.setBorder(null);
        bg.add(jP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 270, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nhập lại mật khẩu");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 270, -1));

        jtxtAddress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 270, 30));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Quê quán");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Số điện thoại");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        jtxtPhone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jtxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 270, 30));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 270, -1));

        jLReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        jLReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLReturnMouseClicked(evt);
            }
        });
        bg.add(jLReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jCbox.setText("<html>Tôi đồng ý với\n");
        bg.add(jCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 100, -1));

        jLabel2.setText("<html> <b>Điều khoản người dùng</b>\n");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 482, -1, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLReturnMouseClicked
        // TODO add your handling code here:
        login loginFrame = new login();
        loginFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jLReturnMouseClicked

    private void jbtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegisterActionPerformed
     // Thu thập dữ liệu từ giao diện
UserDTO dto = new UserDTO();
dto.setEmail(jtxtEmail.getText());
dto.setFullName(jtxtFullName.getText());
String password = new String(jP1.getPassword()); // Mật khẩu chính
String confirmPassword = new String(jP2.getPassword()); // Mật khẩu xác nhận
dto.setPassword(password);
dto.setPhone(jtxtPhone.getText());
dto.setAddress(jtxtAddress.getText());

// Kiểm tra mật khẩu và mật khẩu xác nhận có trùng không
if (!password.equals(confirmPassword)) {
    JOptionPane.showMessageDialog(this, "Mật khẩu và xác nhận mật khẩu không trùng khớp!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    return;
}

// Sử dụng Hibernate Validator để kiểm tra các trường khác
ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
Validator validator = factory.getValidator();
Set<ConstraintViolation<UserDTO>> violations = validator.validate(dto);

// Kiểm tra lỗi và dừng ngay khi gặp lỗi đầu tiên
for (ConstraintViolation<UserDTO> violation : violations) {
    JOptionPane.showMessageDialog(this, violation.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    return; // Dừng lại ngay sau khi thông báo lỗi đầu tiên
}

// Nếu không có lỗi nào, thực hiện tiếp tục xử lý
try {
    customers cs = new customers();
    if (cs.registerCustomer(dto.getEmail(), dto.getPassword(), dto.getFullName(), dto.getPhone(), dto.getAddress())) {
        JOptionPane.showMessageDialog(this, "Đăng ký thành công!");
        this.dispose();
        login frmLogin = new login();
        frmLogin.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Đăng ký thất bại. Vui lòng thử lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jbtnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JCheckBox jCbox;
    private javax.swing.JLabel jLReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jP1;
    private javax.swing.JPasswordField jP2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jbtnRegister;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFullName;
    private javax.swing.JTextField jtxtPhone;
    // End of variables declaration//GEN-END:variables
}
