/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.CustomerLayout;

import Pojo.Product;
import Process.product;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author An Ninh
 */
public class CustomerProducts extends javax.swing.JPanel {
    private List<Product> productList = new ArrayList<>(); // Danh sách sản phẩm
    private  product pr = new product();
    /**
     * Creates new form CustomerProducts
     */
    public CustomerProducts() {
        initComponents();
        loadProducts();
    }
    

   private void loadProducts() {
    // Xóa nội dung cũ nếu có
    jScrollPane1.getViewport().removeAll();

    // Tạo JPanel để chứa các hàng sản phẩm
    JPanel listPanel = new JPanel();
listPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10)); // Sắp xếp ngang, cách nhau 10px

    // Tạo đối tượng product và gọi phương thức getAllProducts
    productList = pr.getAllProducts(); // Lấy tất cả sản phẩm từ cơ sở dữ liệu

    // Tạo các hàng và thêm vào giao diện
    for (Product product : productList) {
        System.out.println(product.toString()); // Log thông tin sản phẩm để kiểm tra

        CustomerProductCard productCard = new CustomerProductCard();
        productCard.setProductData(product); // Truyền dữ liệu sản phẩm vào card
        listPanel.add(productCard);
    }

    // Đặt JPanel vào JScrollPane
    jScrollPane1.setViewportView(listPanel);

    // Làm mới giao diện
    listPanel.revalidate();
    listPanel.repaint();
}
     
       private void jFilterProductMouseClicked(java.awt.event.MouseEvent evt) {
        // Lọc sản phẩm dựa trên các bộ lọc đã chọn
        String category = (String) jBoxCate.getSelectedItem();
        String status = (String) jBoxStatus.getSelectedItem();
        String priceRange = (String) jBoxRangePrice.getSelectedItem();
        String name = jTextField1.getText();

        List<Product> filteredProducts = filterProducts(category, status, priceRange, name);
        displayFilteredProducts(filteredProducts);
    }

    private List<Product> filterProducts(String category, String status, String priceRange, String name) {
        // Giả lập phương thức lọc sản phẩm dựa trên các tiêu chí
        List<Product> filteredProducts = new ArrayList<>();
        for (Product product : productList) {
            boolean matches = true;

            if (!category.equals("Tất cả") && !product.getIdCate().equals(category)) {
                matches = false;
            }
            if (!status.equals("Tất cả") && !product.getStatus().equals(status)) {
                matches = false;
            }
            if (!priceRange.equals("Tất cả")) {
                // Lọc theo giá (Giả sử có một số khoảng giá cụ thể)
                if (priceRange.equals("Dưới 200")) {
                    if (product.getPrice() >= 200) matches = false;
                } else if (priceRange.equals("Trên 200")) {
                    if (product.getPrice() < 200) matches = false;
                }
            }
            if (!name.isEmpty() && !product.getName().toLowerCase().contains(name.toLowerCase())) {
                matches = false;
            }

            if (matches) {
                filteredProducts.add(product);
            }
        }
        return filteredProducts;
    }

    private void displayFilteredProducts(List<Product> filteredProducts) {
        // Xóa nội dung cũ nếu có
        jScrollPane1.getViewport().removeAll();

        // Tạo JPanel để chứa các hàng sản phẩm đã lọc
        JPanel listPanel = new JPanel();
        listPanel.setLayout(new javax.swing.BoxLayout(listPanel, javax.swing.BoxLayout.Y_AXIS));

        // Tạo các thẻ sản phẩm cho các sản phẩm đã lọc và thêm vào giao diện
        for (Product product : filteredProducts) {
            CustomerProductCard productCard = new CustomerProductCard();
            productCard.setProductData(product); // Truyền dữ liệu sản phẩm vào card
            listPanel.add(productCard);
        }

        // Đặt JPanel vào JScrollPane
        jScrollPane1.setViewportView(listPanel);

        // Làm mới giao diện
        listPanel.revalidate();
        listPanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBoxCate = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBoxStatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jBoxRangePrice = new javax.swing.JComboBox<>();
        jSeacrhProduct = new javax.swing.JLabel();
        jFilterProduct = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jBoxCate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Danh mục:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Trạng thái:");

        jBoxStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Giá:");

        jBoxRangePrice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeacrhProduct.setBackground(new java.awt.Color(51, 51, 51));
        jSeacrhProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSeacrhProduct.setForeground(new java.awt.Color(255, 255, 255));
        jSeacrhProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSeacrhProduct.setText("Tìm kiếm");
        jSeacrhProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSeacrhProduct.setOpaque(true);

        jFilterProduct.setBackground(new java.awt.Color(51, 51, 51));
        jFilterProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFilterProduct.setForeground(new java.awt.Color(255, 255, 255));
        jFilterProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFilterProduct.setText("Lọc");
        jFilterProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jFilterProduct.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tên :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBoxRangePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBoxCate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFilterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeacrhProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(124, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoxStatus)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoxRangePrice)
                    .addComponent(jFilterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoxCate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeacrhProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBoxCate;
    private javax.swing.JComboBox<String> jBoxRangePrice;
    private javax.swing.JComboBox<String> jBoxStatus;
    private javax.swing.JLabel jFilterProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSeacrhProduct;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
