/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.CustomerLayout;

import Database.ActionOrders;
import Pojo.Order;
import Pojo.OrderItem;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author An Ninh
 */
public class CustomerOrderCard extends javax.swing.JPanel {

    private Order order; // Dữ liệu đơn hàng
    private int index; // Đối số số thứ tự cho đơn hàng
    private ActionOrders Ao;

    /**
     * Creates new form CustomerOrderCard
     */
    
     public CustomerOrderCard() {
        initComponents();

    }
    
    public CustomerOrderCard(Order order) {
        this.order = order;
        initComponents();
        loadData();
    }
    
        public CustomerOrderCard(int index, Order order, ActionOrders Ao) {
        this.index = index;
        this.Ao = Ao;
        this.order = order;
        initComponents();
        loadData();
    }
        
            public void setIndex(int index) {
        this.index = index;
        idOrder.setText(String.valueOf(index));
    }
    
     private void loadData() {
             System.out.println("Loading data for Order ID: " + order.getIdOrder());
        setOrderData(order);
    }
     
     private void setOrderData(Order order) {
    if (order != null) {
            // Cập nhật các thông tin đơn hàng
            idOrder.setText(String.valueOf(order.getIdOrder()));  // Hiển thị ID đơn hàng
            nameProduct.setText(order.getName()); // Hiển thị tên người mua
            jAddress.setText(order.getAddress()); // Hiển thị địa chỉ
            jPhone.setText(order.getPhone()); // Hiển thị số điện thoại
            jTimeOrder.setText(order.getFormattedCreatedAt()); // Hiển thị ngày mua (Timestamp)
            jTimeOrder.setToolTipText(order.getAddress()); // Tooltip cho Địa chỉ

            // Xử lý hiển thị sản phẩm
            StringBuilder productNames = new StringBuilder();
            List<OrderItem> items = order.getOrderItems();
            if (items == null || items.isEmpty()) {
                productNames.append("Không có sản phẩm");
            } else {
                for (OrderItem item : items) {
                    productNames.append(item.getProductName()).append(", ");
                }
                // Loại bỏ dấu phẩy cuối cùng
                productNames.setLength(productNames.length() - 2);
            }
            nameProduct.setText(productNames.toString());
            nameProduct.setToolTipText(productNames.toString());

            // Cập nhật trạng thái đơn hàng
            updateApprovalStatus(order.getStatus());

        } else {
            // Nếu order là null, hiển thị thông báo
            System.out.println("Order is null");
        }
}
     
     private void updateApprovalStatus(int status) {
        switch (status) {
            case 0:
                jAction.setText("Chờ xét duyệt");
                jAction.setBackground(Color.orange);
                break;
            case 1:
                jAction.setText("Đang giao hàng");
                jAction.setBackground(Color.green);
                break;
            case 2:
                jAction.setText("Đơn hàng bị hủy");
                jAction.setBackground(Color.red);
                break;
            default:
                jAction.setText("Trạng thái không xác định");
                jAction.setBackground(Color.gray);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        idOrder = new javax.swing.JLabel();
        nameProduct = new javax.swing.JLabel();
        jAddress = new javax.swing.JLabel();
        jPhone = new javax.swing.JLabel();
        jTimeOrder = new javax.swing.JLabel();
        jAction = new javax.swing.JLabel();
        jSelect = new javax.swing.JRadioButton();

        jRadioButton1.setText("jRadioButton1");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idOrder.setText("Mã đơn");
        jPanel1.add(idOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 81, 54));

        nameProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameProduct.setText("Tên sản phẩm");
        jPanel1.add(nameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 0, 97, 54));

        jAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddress.setText("Địa chỉ");
        jPanel1.add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 93, 54));

        jPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPhone.setText("Số điện thoại");
        jPanel1.add(jPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 93, 54));

        jTimeOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTimeOrder.setText("Ngày đặt");
        jPanel1.add(jTimeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 93, 54));

        jAction.setBackground(new java.awt.Color(255, 0, 0));
        jAction.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jAction.setForeground(new java.awt.Color(255, 255, 255));
        jAction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAction.setText("Hủy ");
        jAction.setOpaque(true);
        jPanel1.add(jAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 60, 60));

        jSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectActionPerformed(evt);
            }
        });
        jPanel1.add(jSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idOrder;
    private javax.swing.JLabel jAction;
    private javax.swing.JLabel jAddress;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPhone;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jSelect;
    private javax.swing.JLabel jTimeOrder;
    private javax.swing.JLabel nameProduct;
    // End of variables declaration//GEN-END:variables
}
