/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.CustomerLayout;

import Pojo.Order;
import java.awt.Color;

/**
 *
 * @author An Ninh
 */
public class CustomerOrderCard extends javax.swing.JPanel {
    private Order order; // Dữ liệu đơn hàng

    /**
     * Creates new form CustomerOrderCard
     */
    public CustomerOrderCard() {
        initComponents();
    }
    
    
    public CustomerOrderCard(Order order) {
        this.order = order;
        initComponents();
        loadData();
    }
    
     private void loadData() {
        setOrderData(order);
    }
     
     private void setOrderData(Order order) {
        idOrder.setText(String.valueOf(order.getIdOrder())); // Hiển thị ID đơn hàng
        nameProduct.setText(order.getItem()); // Tên sản phẩm
        jAddress.setText(order.getAddress()); // Địa chỉ
        jPhone.setText(order.getPhone()); // Số điện thoại
        jTimeOrder.setText(order.getFormattedCreatedAt()); // Ngày đặt hàng

        // Hiển thị trạng thái của đơn hàng do admin thay đổi
        updateApprovalStatus(order.getIsApproved());
    }
     
     private void updateApprovalStatus(int isApproved) {
        switch (isApproved) {
            case 0:
                jAction.setText("Chờ xét duyệt");
                jAction.setBackground(Color.orange);
                break;
            case 1:
                jAction.setText("Đang giao hàng");
                jAction.setBackground(Color.green);
                break;
            case 2:
                jAction.setText("Đơn hàng bị hủy");
                jAction.setBackground(Color.red);
                break;
            default:
                jAction.setText("Trạng thái không xác định");
                jAction.setBackground(Color.gray);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        idOrder = new javax.swing.JLabel();
        nameProduct = new javax.swing.JLabel();
        jAddress = new javax.swing.JLabel();
        jPhone = new javax.swing.JLabel();
        jTimeOrder = new javax.swing.JLabel();
        jAction = new javax.swing.JLabel();
        jSelect = new javax.swing.JRadioButton();

        jRadioButton1.setText("jRadioButton1");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idOrder.setText("Mã đơn");
        jPanel1.add(idOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 81, 54));

        nameProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameProduct.setText("Tên sản phẩm");
        jPanel1.add(nameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 0, 97, 54));

        jAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddress.setText("Địa chỉ");
        jPanel1.add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 93, 54));

        jPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPhone.setText("Số điện thoại");
        jPanel1.add(jPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 93, 54));

        jTimeOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTimeOrder.setText("Ngày đặt");
        jPanel1.add(jTimeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 93, 54));

        jAction.setBackground(new java.awt.Color(255, 0, 0));
        jAction.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jAction.setForeground(new java.awt.Color(255, 255, 255));
        jAction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAction.setText("Hủy ");
        jAction.setOpaque(true);
        jPanel1.add(jAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 60, 60));

        jSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectActionPerformed(evt);
            }
        });
        jPanel1.add(jSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idOrder;
    private javax.swing.JLabel jAction;
    private javax.swing.JLabel jAddress;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPhone;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jSelect;
    private javax.swing.JLabel jTimeOrder;
    private javax.swing.JLabel nameProduct;
    // End of variables declaration//GEN-END:variables
}
